### ISSUE TITLE
look

### ISSUE THREAD

**Issue by Gomesz785** [fgsl/mock-consumer#5]
https://github.com/fgsl/eyedatagrid/issues/4

**Comment by fgsl** [comment]
Hi, @Gomesz785 . I understand you have opened this issue to have my attention. I think that other notification should be sent to Spam folder. Then I am closing this because I already answer you there.

**Comment by fgsl** [comment]
> [fgsl/eyedatagrid#4](https://github.com/fgsl/eyedatagrid/issues/4)

Answered.

**Comment by Gomesz785** [comment]
> Hi, @Gomesz785 . I understand you have opened this issue to have my attention. I think that other notification should be sent to Spam folder. Then I am closing this because I already answer you there.

Thanks for being so understanding, Yes, It should be spam, but I was in a real hurry to get answers.
